# --- !Ups

create table "images" (
  "id" bigint generated by default as identity(start with 1) not null primary key,
  "name" varchar not null,
  "path" varchar not null,
  "detectionEnabled" boolean not null default false
);

# --- !Downs

drop table "images" if exists;
